Add tests section
SSSD/sssd.io pull request #1
Opened 2021-01-29 15:03 UTC by justin-stephenson

2021-02-08 09:19 UTC, pbrezina requested changes

2021-02-08 09:19 UTC, pbrezina commented on src/contrib/tests/unit-tests.rst
> +
Add files and code into double backquotes:
```
``code``
``` 

This will make it an inline code.

2021-02-08 09:19 UTC, pbrezina commented on src/contrib/tests/unit-tests.rst
> +A less typical use-case is testing of the NSS or PAM responders in isolation. The NSS responder test is located at `src/tests/cmocka/test_nss_srv.c`. Normally, the NSS responder would require a clien
End parentheses is missing after mock_input_user_or_group.

2021-02-08 09:19 UTC, pbrezina commented on src/contrib/tests/integration-tests.rst
> +The advantage over the unit tests is obvious, the full deamon is ran and you can talk to the SSSD using the same interfaces as a user would do in production, e.g. resolve a user with `getpwnam`. Beca
is is -> it is

2021-02-08 09:19 UTC, pbrezina commented on src/contrib/tests/integration-tests.rst
> +To see an example of adding test cases to existing tests, see commit `76ce965fc3abfdcf3a4a9518e57545ea060033d6` or for an example of adding a whole new test, including faking the client library (whic
Link commit to github.

2021-02-08 09:19 UTC, pbrezina commented on src/contrib/tests/multihost-tests.rst
> +First, the infrastructure does not yet concern itself with provisioning at all. You need to set up a VM to run the tests on yourself. As an example, we'll be running the tests on a Fedora 28 machine
Can we replace it with an example of running multihost test on sssd-test-suite?

2021-02-08 09:19 UTC, pbrezina commented on src/contrib/running-tests.rst
> +* :ref:`multihost-tests`
Replace this with:
```
.. toctree::
    :maxdepth: 0
    :titlesonly:

    tests/unit-tests
    tests/integration-tests
    tests/multihost-tests
```

Then you can remove `type-list` completely.

2021-02-08 16:14 UTC, justin-stephenson commented
Thank you for the review, all items should be fixed now.

2021-02-08 16:59 UTC, pbrezina commented on src/contrib/tests/multihost-tests.rst
> +First, the infrastructure does not yet concern itself with provisioning at all. You need to set up a VM to run the tests on yourself. As an example, we'll be running the tests on a Fedora 28 machine
You don't need to setup the root password now with sssd-test-suite. Also it is not currently possible to run other tests then `basic` (well it is possible but not straighforward, I still need to work on that). So only basic tests should be run now and you need to specify the directory so other tests are not picked up (it is currently not possible to run pytest from the root multihost dir).

Check this for guide: https://github.com/SSSD/sssd/blob/master/src/tests/multihost/README.md
But perhaps keep including the virtual environment (with a meaningful name?)

2021-02-08 16:59 UTC, pbrezina commented
Thank you, I still have some comments to the multihost tests but it looks good otherwise.

2021-02-09 18:25 UTC, justin-stephenson commented
Please see the latest multihost changes

2021-02-10 11:01 UTC, pbrezina commented on src/contrib/tests/multihost-tests.rst
> +    sudo pip3 install -r src/tests/multihost/requirements.txt
Remove sudo because you are in python venv.

2021-02-10 11:02 UTC, pbrezina requested changes
One last change and we can merge it.

2021-02-10 16:00 UTC, justin-stephenson commented
> One last change and we can merge it.

Updated, thanks.

2021-02-11 10:30 UTC, pbrezina commented
Thank you. Ack.

2021-02-11 11:09 UTC, merged