Add cache req document
SSSD/sssd.io pull request #21
Opened 2021-03-23 17:37 UTC by justin-stephenson

I wrote this based on my understanding of reading the code, please let me know if I missed any important components and I will add it. For example I did not give a detailed explanation about domain selection/location codepaths.

2021-03-25 12:54 UTC, pbrezina commented
I think this is a good start but imho the focus is different then what it should be.

The target reader is a developer (external and internal) who wants to contribute to the project and use cache_req in his code or even implement a cache_req plugin. So I think you don't need to focus on the NSS responder at all, but put all energy into describing the cache_req in detail - not only the basic search but all the details that happens under the hood, all the plugins capabilities and switches and so on.

The goal is to really describe how it works under the hood - even I don't understand it completely since it changed a lot from the time I wrote it :-) And ideally, make it easily maintenable.

BTW I described the basic lookup in SSSD architecture, you can just link it from this document when its merged and focus on details here.

2021-03-25 12:56 UTC, pbrezina commented
I think this document should consist from two parts:

1. How to use cache_req API
2. What happens under the hood and how to write new plugins and extend functionality

2021-03-25 13:36 UTC, justin-stephenson commented
Thank you, I'll re-work the document and submit an update once done.

2021-03-26 08:57 UTC, pbrezina commented
> > I think this document should consist from two parts:
> > ```
> > 1. How to use cache_req API
> > ```
> 
> From internally within SSSD is acceptable? Or is this intended to be an external API for any application to call?

Internal only.

> > What happens under the hood and how to write new plugins and extend functionality
> 
> I thought that a cache_req plugin exists to handle each type of NSS library call, what would be the use case for writing a new plugin? Is `CACHE_REQ_USER_BY_CERT` an example of this type of use case?

It's not only about nss, it handles everything (expect sudo for now). So if something new is added, it needs to get support in cache req.

2021-03-29 11:02 UTC, pbrezina commented
Perhaps, we can split it into two documents:
* how to use cache req API into "fundamentals" section
* how does it work internally into "under the hood" section

2021-03-30 01:32 UTC, elkoniu commented on src/contrib/cache_req.rst
> +	graph LR
This chart looks "too flat" to me. I think similar to the one [1] made by jhrozek in the past would be more meaningful.
[1] https://jhrozek.files.wordpress.com/2015/03/sssd-lookup.png

2021-03-30 01:32 UTC, elkoniu commented on src/contrib/cache_req.rst
> +``nss_cmd_getgrgid(``) sets ``CACHE_REQ_GROUP_BY_ID()``, etc...
I think I would put here full definition of `enum cache_req_type` in some scrollable box or table with some mappings in between functions and `cache_req` types.

2021-03-30 01:32 UTC, elkoniu commented on src/contrib/cache_req.rst
> +.. code-block:: sssd-log
This code snippet not fits the description above.

2021-03-30 01:32 UTC, elkoniu commented on src/contrib/cache_req.rst
> +	*[cache_req_search_domains] (0x0400): CR #23: Search will check the cache and check the data provider*
This should be `sssd-log` snippet I think.

2021-03-30 01:32 UTC, elkoniu commented on src/contrib/cache_req.rst
> +.. mermaid::
I would use a different graph skin for the control flow and a different one for the data flow.

2021-03-30 01:32 UTC, elkoniu commented on src/contrib/cache_req.rst
> +* First the search checks the negative cache(``cache_req_user_by_name_ncache_check()``)
Graph mixed with bullet list and log snippets make this chapter content a bit hard to follow.

2021-03-30 14:22 UTC, justin-stephenson commented
I did a large rewrite of the document, I believe it is more aligned with the expected content now.

I would appreciate help in completing writing about the ``Well known object`` code and proper use of the cache_req plugin well_known_fn - I did not really understand what this code does, or what problem is solves.

Thank you for the review @elkoniu but I suspect your review items may not be relevant anymore as I removed most of the previous content.

2021-04-12 14:04 UTC, pbrezina requested changes
cache_req -> \``cache_req``

Minor comments in review. You did a good job there.

2021-04-12 14:04 UTC, pbrezina commented on src/contrib/cache_req.rst
> +The domain locator plugin exists to alleviate performance problems when SSSD must iterate over several domains(ex: AD forest with multiple domains) for each unqualified name, or by-ID lookups. The do
each unqualified name, or by-ID lookups -> each unqualified name or by-ID lookups

2021-04-12 14:04 UTC, pbrezina commented on src/contrib/cache_req.rst
> +The send function sends a SBUS ``getAccountDomain`` request to the backend, if a domain is reported as containing an object, all domains except that
a SBUS -> an SBUS

2021-04-12 14:04 UTC, pbrezina commented on src/contrib/cache_req.rst
> +one are marked with negative cache entries for that request(using the associated ``.ncache_add_fn`` plugin function``.
plugin function``. -> plugin function.

2021-04-12 14:04 UTC, pbrezina commented on src/contrib/cache_req.rst
> +The domain locator plugin code is only executed for unqualified requests with multiple domains, or on the second pass of a ``CACHE_REQ_CACHE_FIRST`` lookup.
domains, or on the -> domains or on the

2021-04-12 14:04 UTC, pbrezina commented on src/contrib/cache_req.rst
> +.. warning::
Place this before or after the note.

2021-04-12 14:05 UTC, pbrezina commented on src/contrib/cache_req.rst
> +    =========================== ====================================
Add a header. It will look better.

2021-04-12 16:06 UTC, justin-stephenson commented
Thanks very much for the review, review items addressed as requested.

2021-04-13 09:46 UTC, pbrezina commented
Ack.

2021-04-13 09:46 UTC, merged