docs: AD Introduction
SSSD/sssd.io pull request #25
Opened 2021-03-31 17:56 UTC by justin-stephenson

2021-04-12 13:23 UTC, pbrezina requested changes
Hi Justin, minor comments are inside.

2021-04-12 13:23 UTC, pbrezina commented on src/docs/ad/ad-introduction.rst
> +Heterogeneous IT environments often contain various domains and operating systems that need to be able to seamlessly communicate. SSSD offers integration with Active Directory on Linux/Unix clients b
In general, SSSD runs on Unix systems to some level but we, developers, have nothing to do with Unix. So perhaps it is better to omit it so we don't advertise a false assumption that we run tests against Unix systems?

2021-04-12 13:23 UTC, pbrezina commented on src/docs/ad/ad-introduction.rst
> +
Make it a list?

* link1
* link2

2021-04-12 13:23 UTC, pbrezina commented on src/docs/ad/ad-introduction.rst
> +.. code-block:: bash
console

2021-04-12 13:23 UTC, pbrezina commented on src/docs/ad/ad-introduction.rst
> +SSSD can also retrieve information and perform authentication against Active Directory Domain Controllers through IPA servers, this is done via IPA - AD Trust - also called ``Indirect AD`` integratio
Italics instead of code? `*Indirect AD*`

2021-04-12 13:23 UTC, pbrezina commented on src/docs/ad/ad-introduction.rst
> +`Integrating IdM and AD. <https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/installing_identity_management/index?lb_target=production#installing-trust-between-idm-a
Make it a list?

2021-04-12 13:26 UTC, pbrezina commented
Also please double  check that the links to Red Hat articles are free to access outside VPN and authorized access.

2021-04-12 13:51 UTC, justin-stephenson commented
All changes made as requested. Links are external.

2021-04-13 09:53 UTC, pbrezina commented
Thank you. Ack.

2021-04-13 09:53 UTC, merged