ldap: add broader introduction to the protocol
SSSD/sssd.io pull request #35
Opened 2021-06-07 13:59 UTC by pbrezina

2021-06-08 13:45 UTC, justin-stephenson requested changes
Minor changes requested.

2021-06-08 13:45 UTC, justin-stephenson commented on src/docs/ldap/ldap-introduction.rst
> +    * **dc**: domain component -- used to identify the directory domain *
intended trailing `*` here?

2021-06-08 13:45 UTC, justin-stephenson commented on src/docs/ldap/ldap-introduction.rst
> +    * **ou**: orgnanizational unit -- used to split entries into named containers
typo: organizational

2021-06-09 10:20 UTC, pbrezina commented on src/docs/ldap/ldap-introduction.rst
> +    * **dc**: domain component -- used to identify the directory domain *
Nope.

2021-06-09 10:22 UTC, pbrezina commented
Thank you. See updated patch.

2021-06-09 14:19 UTC, justin-stephenson commented on src/docs/ldap/ldap-introduction.rst
> +directory servers. It explains the very basics that will help you dive into the
s/the directory servers/directory servers/

2021-06-09 14:21 UTC, justin-stephenson commented
Ack with the last single change.

2021-06-09 14:58 UTC, pbrezina commented
Done. Thank you.

2021-06-09 14:58 UTC, merged