ipa: improve the introduction
SSSD/sssd.io pull request #38
Opened 2021-07-15 15:03 UTC by pbrezina

2021-07-16 17:31 UTC, justin-stephenson commented on src/docs/ipa/ipa-introduction.rst
> +protocols into single complex identity management solution. It provides much
s/into single/into a single/

2021-07-16 17:31 UTC, justin-stephenson commented on src/docs/ipa/ipa-introduction.rst
> +richer experience when compared to native LDAP solutions such as:
s/provides much richer/provides a much richer/

2021-07-16 17:32 UTC, justin-stephenson commented on src/docs/ipa/ipa-introduction.rst
> +richer experience when compared to native LDAP solutions such as:
s/such as/including features such as/

2021-07-16 17:33 UTC, justin-stephenson commented on src/docs/ipa/ipa-introduction.rst
> +    SSSD is the main FreeIPA client therefore it provides the full experience
s/provides/supports/

2021-07-16 17:33 UTC, justin-stephenson commented on src/docs/ipa/ipa-introduction.rst
> +    and always provides every new feature at the same time when it becomes
s/provides/supports/

2021-07-16 17:36 UTC, justin-stephenson commented on src/docs/ipa/ipa-introduction.rst
> +then available on FreeIPA enrolled host (which also means that Active Directory
s/host/hosts/

2021-07-16 17:36 UTC, justin-stephenson commented on src/docs/ipa/ipa-introduction.rst
> +* Host-Based Access Controllers (HBAC)
s/Controllers/Control/ ?

2021-07-16 17:39 UTC, justin-stephenson requested changes
Minor changes added, overall LGTM.

2021-07-19 10:28 UTC, pbrezina commented
Thank you. Please, see new patches.

2021-07-19 12:30 UTC, justin-stephenson commented
Ack.

2021-07-19 13:01 UTC, merged