Add troubleshooting basics + provider docs
SSSD/sssd.io pull request #9
Opened 2021-02-23 16:58 UTC by justin-stephenson

* Moved some sections around
* Removed section about joining a domain (covered already in other doc)
* Split `common AD/LDAP/IPA provider` sections into separate individual docs, not sure if this is the best approach. Perhaps these can be combined into a single page 'Common issues' 
* Removed man page links to `https://jhrozek.fedorapeople.org/sssd/1.14.0/man`

Once the troubleshooting backend document is updated/merged, it probably makes sense to move the section `Troubleshooting general sssd_be problems` from here into that doc

2021-03-02 15:18 UTC, pbrezina commented
Please, use "sssd-log" lexer instead of "bash" for logs. Otherwise LGTM.

2021-03-02 21:27 UTC, justin-stephenson commented
New version pushed, thanks.

2021-03-03 11:31 UTC, pbrezina requested changes
Minor comments.

2021-03-03 11:31 UTC, pbrezina commented on src/troubleshooting/ad_provider.rst
> +###########################
Underline too long.

2021-03-03 11:31 UTC, pbrezina commented on src/troubleshooting/basics.rst
> +*****************************
Underline too long.

2021-03-03 11:31 UTC, pbrezina commented on src/troubleshooting/ipa_provider.rst
> +############################
Underline too long.

2021-03-03 11:31 UTC, pbrezina commented on src/troubleshooting/ldap_provider.rst
> +#############################
Underline too long.

2021-03-03 15:57 UTC, justin-stephenson commented
Issues are fixed now.

2021-03-04 10:32 UTC, pbrezina commented
Thank you.Ack.

2021-03-04 10:32 UTC, merged